target 'Cristoforo Colombo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cristoforo Colombo

pod "SAConfettiView"

end
